In [1]:
import numpy as np

In [7]:
arr = np.arange(5)

In [8]:
arr

array([0, 1, 2, 3, 4])

In [9]:
np.save('myarray',arr)

In [10]:
arr = np.arange(10)

In [11]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.load('myarray.npy') #don't forget npy extension

array([0, 1, 2, 3, 4])

In [14]:
arr1 = np.load('myarray.npy')

In [15]:
arr2 = arr

In [16]:
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
np.savez('ziparray.npz',x = arr1,y = arr2)

In [21]:
archive_array = np.load('ziparray.npz')

In [25]:
archive_array['x']

array([0, 1, 2, 3, 4])

In [28]:
archive_array['y']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
arr = np.array([[1,2,3],[4,5,6]])

In [32]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [34]:
np.savetxt('mytextarray.txt',arr,delimiter = ',')

In [37]:
arr = np.loadtxt('mytextarray.txt',delimiter = ',')

In [38]:
arr

array([[1., 2., 3.],
       [4., 5., 6.]])