In [2]:
import numpy as np

In [5]:
from __future__ import division

In [7]:
5/2

2.5

In [10]:
ar_1 = np.array([[1,2,3,4],[8,9,10,11]])

In [11]:
ar_1

array([[ 1,  2,  3,  4],
       [ 8,  9, 10, 11]])

In [12]:
ar_1*ar_1

array([[  1,   4,   9,  16],
       [ 64,  81, 100, 121]])

In [14]:
ar_1 - 1

array([[ 0,  1,  2,  3],
       [ 7,  8,  9, 10]])

In [16]:
ar_1 / 10

array([[0.1, 0.2, 0.3, 0.4],
       [0.8, 0.9, 1. , 1.1]])

In [1]:
ar_1 ** 2 #numbers in the array will get exponent to the number you add here.

NameError: name 'ar_1' is not defined

In [5]:
arr = np.arange(0,11) #left argument shows the beginning and right argument shows the number of numbers ha!

In [7]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
arr[8]

8

In [11]:
arr[1:5]

array([1, 2, 3, 4])

In [13]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [21]:
arr[0:5] = 100 #this converts first 5 digits into 100, but 6th digit will use the original argument

In [22]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [6]:
arr[0:5] = 10

In [7]:
arr

array([10, 10, 10, 10, 10,  5,  6,  7,  8,  9, 10])

In [9]:
arr = np.arange(0,11)

In [11]:
slice_of_arr = arr[0:6]

In [13]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [15]:
slice_of_arr[:] = 99 #: is all the elements in the assigned value

In [17]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [19]:
arr #here row15's direction remains the whole arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [21]:
arr_copy = arr.copy() #.copy() dupicates the left side of .(dot)

In [23]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [26]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))


arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [28]:
arr_2d[1]

array([20, 25, 30])

In [30]:
arr_2d[0]

array([ 5, 10, 15])

In [32]:
arr_2d[1][0] #first braket is for row and the second one is for column

20

In [44]:
arr_2d[:2,1:] #:2 includes 0 and 1 rows but not including 2nd row.
#1: gives second row and to the end, which is 2 in this case. *Python starts count from 0.

array([[10, 15],
       [25, 30]])

In [46]:
arr_2d[2]

array([35, 40, 45])

In [49]:
arr_2d = np.zeros((10,10))
arr_2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [52]:
arr_length = arr_2d.shape[1]
arr_length

10

In [57]:
for i in range(arr_length):
    arr_2d[i] = i

In [59]:
arr_2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [60]:
arr_2d[[2,4,6,8,]]

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])