In [2]:
import numpy as np

In [3]:
my_list = [1,2,3,4]

In [5]:
my_array1 = np.array(my_list)

In [7]:
my_array1

array([1, 2, 3, 4])

In [9]:
my_list2 = [11,22,33,44]

In [12]:
my_lists = [my_list,my_list2]

In [15]:
my_array2 = np.array(my_lists)

In [17]:
my_array2

array([[ 1,  2,  3,  4],
       [11, 22, 33, 44]])

In [18]:
my_array2.shape

(2, 4)

In [20]:
my_array2.dtype

dtype('int64')

In [22]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [24]:
my_zeros_array = np.zeros(5)

In [26]:
my_zeros_array.dtype

dtype('float64')

In [28]:
np.ones([5,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [30]:
np.empty(5)

array([0., 0., 0., 0., 0.])

In [32]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [34]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [36]:
np.arange(5,50,2)

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37,
       39, 41, 43, 45, 47, 49])