In [5]:
import numpy as np

In [8]:
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [12]:
np.exp(arr) #exponential

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [20]:
A = np.random.randn(10)
A

array([-1.37484853,  1.31759451, -0.15528407, -1.07477048,  0.32893588,
       -0.13115256, -1.1253533 ,  2.22853807,  1.65519579,  0.7881845 ])

In [23]:
B = np.random.randn(10)
B

array([-0.48006128,  0.58261708,  1.08990605, -0.5046395 , -0.13668424,
        0.92065583, -1.36964971, -0.79380469, -0.55741454,  1.12775209])

In [25]:
# binary functions
np.add(A,B)

array([-1.8549098 ,  1.90021159,  0.93462198, -1.57940998,  0.19225164,
        0.78950327, -2.49500301,  1.43473338,  1.09778124,  1.9159366 ])

In [27]:
np.maximum(A,B) # find a max value from the array

array([-0.48006128,  1.31759451,  1.08990605, -0.5046395 ,  0.32893588,
        0.92065583, -1.1253533 ,  2.22853807,  1.65519579,  1.12775209])

In [30]:
np.minimum(A,B) #find a min value from the array

array([-1.37484853,  0.58261708, -0.15528407, -1.07477048, -0.13668424,
       -0.13115256, -1.36964971, -0.79380469, -0.55741454,  0.7881845 ])

In [35]:
website = 'https://www.csis.org/events'
import webbrowser
webbrowser.open(website)

True